sessions_secret: x7xC8ScVWqhaLWT-7xZhL3QeV9T86r1ChSlUTpJLBhI
postgres:
  url: "postgresql+psycopg2://trotto-user:6-b:M[r,+g)aD-"I@/trotto-dev?host=/cloudsql/fluxon-alloc-dash:us-west1:allox-main"
admins:
  - pratyusha.gogulapati@fluxon.com
  - lasersox@fluxon.com
  - edgard@fluxon.com
